#!/usr/bin/env bash

function has { opam config var "${1}:installed"; }

topkg build -- \
  --with-lwt $(has 'lwt') \
  --with-async $(has 'async') \
  --xen $(has 'mirage-xen') \
  --freestanding $(has 'ocaml-freestanding') \
  $@
